services:
  app-db:
    # Pinned version for better stability, rahter than using postgres:latest, which could cause inconsistency between different dev environments
    image: postgres:18.1
    container_name: expenseledger-db
    # These should be overriden by the actualy db initialization credentials, which should be identical to the env varaibles
    environment:
      POSTGRES_DB: expense_ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
     # Map the host 5432 port to the container's 5432, That means that any request from the host maching for port 5432 will be mapped to the container's 5432 
    ports:
      - "5432:5432"
     # Mounting the docker's volume to the container's files that persist data, since the data is disposed after closing the image, this volume will persist everything in docker's file system
    volumes:
      - app_db_data:/var/lib/postgresql/data

  hangfire-db:
    image: postgres:18.1
    container_name: expense_ledger-hangfire-db
    environment:
      POSTGRES_DB: hangfire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - hangfire_db_data:/var/lib/postgresql/data

  minio:
    image: "minio/minio:RELEASE.2025-04-22T22-12-26Z"
    container_name: minio
    # The command for running the service inside the container 
    command: [ "server", "--console-address", ":9001", "/data" ]
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    ports:
    # The port for the service itself
      - "9000:9000"
    # The port for the dashboard (runs independently from the Api)
      - "9001:9001"

volumes:
  app_db_data:
  hangfire_db_data:
  minio_data: