namespace Application.ErrorNamespace.ErrorCodesNamespace
{
    public static class ExpensesErrorCodes
    {
        public const string EXPENSE_CATEGORY_NOT_FOUND = "EXPENSE_CATEGORY_NOT_FOUND";
        public const string EXPENSE_NOTE_NOT_FOUND = "EXPENSE_NOTE_NOT_FOUND";

        public const string EXPENSE_CATEGORIES_DO_NOT_BELONG_TO_EACH_OTHER = "EXPENSE_CATEGORIES_DO_NOT_BELONG_TO_EACH_OTHER";

        public const string SCHEDULED_EXPENSE_NOT_FOUND = "SCHEDULED_EXPENSE_NOT_FOUND";
        public const string SCHEDULED_EXPENSE_DELETED = "SCHEDULED_EXPENSE_DELETED";
        public const string SCHEDULED_EXPENSE_NOT_ACTIVE = "SCHEDULED_EXPENSE_NOT_ACTIVE";
        public const string SCHEDULED_EXPENSE_PROCESSED_BEFORE_AND_CANNOT_CHANGE_FIRST_DUE = "SCHEDULED_EXPENSE_PROCESSED_BEFORE_AND_CANNOT_CHANGE_FIRST_DUE";
        public const string GENERATED_EXPENSE_FOR_THAT_DAY_ALREADY_EXISTS = "GENERATED_EXPENSE_FOR_THAT_DAY_ALREADY_EXISTS";

        public const string EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND";
        public const string EXPENSE_ALREADY_HAS_A_FILE = "EXPENSE_ALREADY_HAS_A_FILE";
        public const string EXPENSE_FILE_NOT_FOUND = "EXPENSE_FILE_NOT_FOUND";
        public const string EXPENSE_FILE_WAS_DELETED = "EXPENSE_FILE_WAS_DELETED";
        public const string EXPENSE_FILE_ALREADY_LINKED_TO_OTHER_EXPENSE = "EXPENSE_FILE_ALREADY_LINKED_TO_OTHER_EXPENSE";
        public const string EXPENSE_INVALID_FILE_STATE = "EXPENSE_INVALID_FILE_STATE";
        public const string EXPENSE_FILE_NOT_UPLOADED_YET = "EXPENSE_FILE_NOT_UPLOADED_YET";
    }
}
