// <auto-generated />
using System;
using Infrastructure.Database.AppDbContextNamespace;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_expense_categories_code");

                    b.ToTable("expense_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExpenseNamespace.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ScheduledExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_expense_id");

                    b.Property<DateOnly?>("ScheduledGenerationDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_generation_date");

                    b.Property<DateOnly>("SpentOn")
                        .HasColumnType("date")
                        .HasColumnName("spent_on");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_category_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_expenses_category_id");

                    b.HasIndex("SubCategoryId")
                        .HasDatabaseName("IX_expenses_sub_category_id");

                    b.HasIndex("ScheduledExpenseId", "ScheduledGenerationDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_expenses_scheduled_expense_id_scheduled_generation_date")
                        .HasFilter("scheduled_expense_id IS NOT NULL");

                    b.HasIndex("UserId", "SpentOn")
                        .HasDatabaseName("IX_expenses_user_id_spent_on");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_expenses_amount", "amount > 0");

                            t.HasCheckConstraint("CK_expenses_scheduled_generation_date_required", "scheduled_expense_id IS NULL OR scheduled_generation_date IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ExpenseSubCategoryNamespace.ExpenseSubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_expense_sub_categories_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_expense_sub_categories_code");

                    b.ToTable("expense_sub_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FileObjectNamespace.ExpenseFileObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_in_bytes");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset>("StartedProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_processing_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("int")
                        .HasColumnName("storage_provider");

                    b.Property<DateTimeOffset>("UploadUrlExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_url_expires_at");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_expenses_file_objects_object_key");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_expenses_file_objects_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_expenses_file_objects_user_id");

                    b.ToTable("expenses_file_objects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NoteNamespace.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("IX_notes_expenses_expense_id");

                    b.ToTable("notes", null, t =>
                        {
                            t.HasCheckConstraint("CK_notes_content_length", "length(content) >= 1 AND length(content) <= 2000");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateOnly?>("BudgetPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("budget_period_start");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int>("Reason")
                        .HasColumnType("int")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ScheduledExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_expense_id");

                    b.Property<Guid?>("SpendingGoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("spending_goal_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_notifications_category_id");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("IX_notifications_expense_id");

                    b.HasIndex("ScheduledExpenseId")
                        .HasDatabaseName("IX_notifications_scheduled_expense_id");

                    b.HasIndex("SpendingGoalId")
                        .HasDatabaseName("IX_notifications_spending_goal_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_notifications_user_id");

                    b.HasIndex("UserId", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_notifications_user_id_deduplication_key");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("IX_notifications_user_id_read_at");

                    b.HasIndex("UserId", "DeletedAt", "CreatedAt")
                        .HasDatabaseName("IX_notifications_user_id_deleted_at_created_at");

                    b.ToTable("notifications", (string)null);
                });

            // COMMENTED OUT: ObjectStorageDeletionRequest is no longer used
            /*
            modelBuilder.Entity("Domain.Entities.ObjectStorageDeletionRequestNamespace.ObjectStorageDeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("int")
                        .HasColumnName("storage_provider");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_object_storage_deletion_requests_object_key");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_object_storage_deletion_requests_processed_at");

                    b.ToTable("object_storage_deletion_requests", (string)null);
                });
            */

            modelBuilder.Entity("Domain.Entities.RefreshTokenNamespace.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("IX_refresh_tokens_revoked_at");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_active_refresh_token_session_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_refresh_tokens_token");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_refresh_tokens_timestamps", "expires_at >= created_at");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ScheduledExpenseNamespace.ScheduledExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("Cadence")
                        .HasColumnType("int")
                        .HasColumnName("cadence");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("FirstDueOn")
                        .HasColumnType("date")
                        .HasColumnName("first_due_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastProcessedAt")
                        .HasColumnType("date")
                        .HasColumnName("last_processed_at");

                    b.Property<DateOnly?>("NextDueOn")
                        .HasColumnType("date")
                        .HasColumnName("next_due_on");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_category_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Cadence")
                        .HasDatabaseName("IX_scheduled_expenses_cadence");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_scheduled_expenses_category_id");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_scheduled_expenses_user_id");

                    b.ToTable("scheduled_expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_scheduled_expenses_active_next_due_on", "is_active = TRUE OR next_due_on IS NULL");

                            t.HasCheckConstraint("CK_scheduled_expenses_amount", "amount > 0");

                            t.HasCheckConstraint("CK_scheduled_expenses_last_processed_at", "last_processed_at IS NULL OR last_processed_at >= first_due_on");

                            t.HasCheckConstraint("CK_scheduled_expenses_next_due_on", "next_due_on IS NULL OR next_due_on >= first_due_on");
                        });
                });

            modelBuilder.Entity("Domain.Entities.SpendingGoalNamespace.SpendingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndsAt")
                        .HasColumnType("date")
                        .HasColumnName("ends_at");

                    b.Property<decimal>("MaximumTargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("maximum_target_amount");

                    b.Property<decimal>("MinimumTargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_target_amount");

                    b.Property<DateOnly>("StartsAt")
                        .HasColumnType("date")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_spending_goals_category_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_spending_goals_user_id");

                    b.HasIndex("UserId", "CategoryId", "StartsAt", "EndsAt")
                        .IsUnique()
                        .HasDatabaseName("UQ_spending_goals_user_category_period");

                    b.ToTable("spending_goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_spending_goals_bounds", "minimum_target_amount > 0 AND maximum_target_amount >= minimum_target_amount");

                            t.HasCheckConstraint("CK_spending_goals_ends_at", "ends_at >= starts_at");
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserCategoryPreferenceNamespace.UserCategoryPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreferenceLevel")
                        .HasColumnType("int")
                        .HasColumnName("preference_level");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("user_category_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserFinancialProfileNamespace.UserFinancialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyNetIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_net_income");

                    b.Property<int>("ResetDay")
                        .HasColumnType("int")
                        .HasColumnName("reset_day");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResetDay")
                        .HasDatabaseName("IX_users_financial_profiles_reset_day");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_users_financial_profiles_user_id");

                    b.ToTable("users_financial_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_financial_profiles_monthly_net_income", "monthly_net_income >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserNamespace.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExpenseNamespace.Expense", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_expenses_expense_categories_category_id");

                    b.HasOne("Domain.Entities.ScheduledExpenseNamespace.ScheduledExpense", "ScheduledExpense")
                        .WithMany("GeneratedExpenses")
                        .HasForeignKey("ScheduledExpenseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_expenses_scheduled_expenses_scheduled_expense_id");

                    b.HasOne("Domain.Entities.ExpenseSubCategoryNamespace.ExpenseSubCategory", "SubCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_expenses_expense_sub_categories_sub_category_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_expenses_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("ScheduledExpense");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ExpenseSubCategoryNamespace.ExpenseSubCategory", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_expense_sub_categories_expense_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.FileObjectNamespace.ExpenseFileObject", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseNamespace.Expense", "Expense")
                        .WithOne("FileObject")
                        .HasForeignKey("Domain.Entities.FileObjectNamespace.ExpenseFileObject", "ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_expenses_file_objects_expenses_expense_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("FileObjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_expenses_file_objects_users_user_id");

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.NoteNamespace.Note", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseNamespace.Expense", "Expense")
                        .WithMany("Notes")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notes_expenses_expense_id");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Domain.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_notifications_expense_categories_category_id");

                    b.HasOne("Domain.Entities.ExpenseNamespace.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_notifications_expenses_expense_id");

                    b.HasOne("Domain.Entities.ScheduledExpenseNamespace.ScheduledExpense", null)
                        .WithMany()
                        .HasForeignKey("ScheduledExpenseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_notifications_scheduled_expenses_scheduled_expense_id");

                    b.HasOne("Domain.Entities.SpendingGoalNamespace.SpendingGoal", null)
                        .WithMany()
                        .HasForeignKey("SpendingGoalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_notifications_spending_goals_spending_goal_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_notifications_users_user_id");
                });

            modelBuilder.Entity("Domain.Entities.RefreshTokenNamespace.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ScheduledExpenseNamespace.ScheduledExpense", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", "Category")
                        .WithMany("ScheduledExpenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_scheduled_expenses_expense_categories_category_id");

                    b.HasOne("Domain.Entities.ExpenseSubCategoryNamespace.ExpenseSubCategory", "SubCategory")
                        .WithMany("ScheduledExpenses")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_scheduled_expenses_expense_sub_categories_sub_category_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("ScheduledExpenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_scheduled_expenses_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SpendingGoalNamespace.SpendingGoal", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", "Category")
                        .WithMany("SpendingGoals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_spending_goals_expense_categories_category_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("SpendingGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_spending_goals_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserCategoryPreferenceNamespace.UserCategoryPreference", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", "Category")
                        .WithMany("UserCategoryPreferences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_category_preferences_expense_categories_category_id");

                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithMany("CategoryPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_category_preferences_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserFinancialProfileNamespace.UserFinancialProfile", b =>
                {
                    b.HasOne("Domain.Entities.UserNamespace.User", "User")
                        .WithOne("FinancialProfile")
                        .HasForeignKey("Domain.Entities.UserFinancialProfileNamespace.UserFinancialProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_users_financial_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ExpenseCategoryNamespace.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("ScheduledExpenses");

                    b.Navigation("SpendingGoals");

                    b.Navigation("SubCategories");

                    b.Navigation("UserCategoryPreferences");
                });

            modelBuilder.Entity("Domain.Entities.ExpenseNamespace.Expense", b =>
                {
                    b.Navigation("FileObject");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Domain.Entities.ExpenseSubCategoryNamespace.ExpenseSubCategory", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("ScheduledExpenses");
                });

            modelBuilder.Entity("Domain.Entities.ScheduledExpenseNamespace.ScheduledExpense", b =>
                {
                    b.Navigation("GeneratedExpenses");
                });

            modelBuilder.Entity("Domain.Entities.UserNamespace.User", b =>
                {
                    b.Navigation("CategoryPreferences");

                    b.Navigation("Expenses");

                    b.Navigation("FileObjects");

                    b.Navigation("FinancialProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ScheduledExpenses");

                    b.Navigation("SpendingGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
