name: Test dev branch with source-tests & container tests

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - "**.[mM][dD]"
      - "Docs/**"
      - "Server/Logs/**"
      - "Server/TestResults/**"
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    - name: Tests
    - uses: ./.github/workflows/ReusableWorkflows/SetupAndRunTests.yaml

  docker-build-and-smoke-tests:
    name: Docker build and smoke tests
    needs: tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
      - uses: actions/checkout@v6

      - name: Build image
        run: |
          IMAGE_TAG=api:${GITHUB_SHA}
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

          docker build \
            --file Server/Dockerfile \
            --tag $IMAGE_TAG \
            Server/

      - name: Start application
        run: |
            IMAGE_TAG=$"{{steps.Checkout.outputs.image_tag}}" docker compose \
            -f .github/docker-compose.ci.yml \
            up -d

      - name: Wait for application
        shell: bash
        run: |
          for i in {1..30}; do
            if curl --fail --silent http://localhost:7000/; then
              echo "Application responded successfully"
              exit 0
            fi

            sleep 2
          done

          echo "Application failed to respond"
          docker compose -f .github/docker-compose.ci.yml logs
          exit 1

      - name: Shutdown
        if: always()
        run: |
          docker compose \
            -f .github/docker-compose.ci.yml \
            down -v



